---
apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: example-gcp-postgres-sql-database
  annotations:
    guide: quickstart
    provider: gcp
spec:
  crossplane:
    version: ">=v1.0.0-0"
  dependsOn:
    - provider: crossplane/provider-gcp
      version: ">=v0.13.0"